#!/usr/bin/env python3
"""Compare the harness records with a baseline run under another compiler.

    harness/compare.py                       # write docs/harness-sizes.md
    harness/compare.py --distil DIR          # build the baseline file from a
                                             # directory of record files

The baseline (harness/baseline/simplicityhl-0.4.1.json) holds, for every
measured spend, program and refusal of the run made with SimplicityHL 0.4.1,
only the figures this comparison needs. Keys, salts and so commitment roots
are random in every run, so roots are not compared here; sizes, cost bounds,
budgets and refusals are.
"""
import argparse
import glob
import json
import os
import sys

HARNESS = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HARNESS)
BASELINE = os.path.join(HARNESS, "baseline", "simplicityhl-0.4.1.json")
RECORDS = os.path.join(HARNESS, "records")
OUT = os.path.join(ROOT, "docs", "harness-sizes.md")

SPEND = ("vsize", "weight", "program_bytes", "witness_bytes", "stack_serialized_bytes",
         "cost_bound_milli_wu", "cost_bound_wu", "budget_wu")
PROGRAM = ("commit_program_bytes", "control_block_bytes")
REFUSAL = ("rpc-error", "reject-reason", "block-error")
OUTCOME = ("expected", "testmempoolaccept", "rpc-error", "confirmed")
FACT = ("rust_bitmachine_executed", "rust_error", "node_testmempoolaccept", "compile_seconds")

TESTS = {"s1": "S1 one key", "s1c": "S1 ceilings (annex)", "s1d": "S1 ceilings (witness data)",
         "s2": "S2 tree node", "s3": "S3 custom signature hash", "s4": "S4 state",
         "s5": "S5 leave one", "s6": "S6 relative timelocks", "s7": "S7 oracle"}


def distil(records):
    out = {}
    for k, v in records.items():
        if not isinstance(v, dict):
            continue
        if "vsize" in v and "program_bytes" in v:
            out[k] = {"kind": "spend", **{f: v[f] for f in SPEND + ("compile_seconds",) if f in v}}
        elif "cmr" in v and "commit_program_bytes" in v:
            out[k] = {"kind": "program", **{f: v[f] for f in PROGRAM if f in v}}
        elif v.get("rejected"):
            out[k] = {"kind": "refusal", **{f: v[f] for f in REFUSAL if f in v}}
        elif "expected" in v:
            d = {f: v[f] for f in OUTCOME if f in v}
            if isinstance(v.get("block"), dict):
                d["mined"] = v["block"].get("mined")
                d["block-error"] = v["block"].get("block-error")
            out[k] = {"kind": "outcome", **d}
        elif any(f in v for f in FACT):
            out[k] = {"kind": "fact", **{f: v[f] for f in FACT if f in v}}
    return out


def load_records(directory):
    res = {}
    for f in sorted(glob.glob(os.path.join(directory, "*.json"))):
        res[os.path.basename(f)[:-5]] = distil(json.load(open(f)))
    return res


def fmt(v):
    return "" if v is None else str(v)


def delta(a, b):
    if isinstance(a, (int, float)) and isinstance(b, (int, float)) and a != b:
        return " (%+d)" % (b - a)
    return ""


def report(base, new, new_version, base_version):
    lines = ["# Harness sizes under two compilers", "",
             "Every figure the regtest harness measures, from a run under the pinned compiler "
             "(SimplicityHL %s) beside the same test run under SimplicityHL %s. "
             "Generated by `harness/compare.py` from `harness/records/` and "
             "`harness/baseline/simplicityhl-%s.json`." % (new_version, base_version, base_version), "",
             "Keys and salts are fresh in every run, so commitment roots differ between runs "
             "and are not compared here; `docs/compiler-roots.md` compares roots for fixed "
             "inputs. A signature is 64 bytes either way, so sizes are comparable.", ""]
    summary = []
    for t, title in TESTS.items():
        b, n = base.get(t, {}), new.get(t, {})
        if not n:
            continue
        common = [k for k in n if k in b]
        spends = [k for k in common if n[k]["kind"] == "spend"]
        progs = [k for k in common if n[k]["kind"] == "program"]
        refusals = [k for k in common if n[k]["kind"] in ("refusal", "outcome")]
        changed_sizes = [k for k in spends + progs
                         if any(n[k].get(f) != b[k].get(f) for f in SPEND + PROGRAM)]
        changed_refusals = [k for k in refusals if n[k] != b[k]]
        summary.append((title, len(spends), len(progs), len(refusals), len(changed_sizes),
                        len(changed_refusals), sorted(set(n) - set(b)), sorted(set(b) - set(n))))

        lines += ["## %s" % title, ""]
        if progs:
            lines += ["| program | committed bytes, %s | committed bytes, %s | control block |" % (base_version, new_version),
                      "|---|---:|---:|---:|"]
            for k in progs:
                lines.append("| `%s` | %s | %s%s | %s |" % (
                    k, fmt(b[k].get("commit_program_bytes")), fmt(n[k].get("commit_program_bytes")),
                    delta(b[k].get("commit_program_bytes"), n[k].get("commit_program_bytes")),
                    fmt(n[k].get("control_block_bytes"))))
            lines.append("")
        if spends:
            lines += ["| spend | vsize %s | vsize %s | program B %s / %s | witness B %s / %s | cost bound WU %s / %s | budget WU %s / %s |"
                      % ((base_version, new_version) + (base_version, new_version) * 4),
                      "|---|---:|---:|---:|---:|---:|---:|"]
            for k in spends:
                x, y = b[k], n[k]
                lines.append("| `%s` | %s | %s%s | %s / %s%s | %s / %s%s | %s / %s%s | %s / %s%s |" % (
                    k, fmt(x.get("vsize")), fmt(y.get("vsize")), delta(x.get("vsize"), y.get("vsize")),
                    fmt(x.get("program_bytes")), fmt(y.get("program_bytes")),
                    delta(x.get("program_bytes"), y.get("program_bytes")),
                    fmt(x.get("witness_bytes")), fmt(y.get("witness_bytes")),
                    delta(x.get("witness_bytes"), y.get("witness_bytes")),
                    fmt(x.get("cost_bound_wu")), fmt(y.get("cost_bound_wu")),
                    delta(x.get("cost_bound_wu"), y.get("cost_bound_wu")),
                    fmt(x.get("budget_wu")), fmt(y.get("budget_wu")),
                    delta(x.get("budget_wu"), y.get("budget_wu"))))
            lines.append("")
        if refusals:
            lines += ["Refusals and outcomes: %d compared, %d identical in every recorded string "
                      "(mempool error, block error, outcome)." % (len(refusals), len(refusals) - len(changed_refusals)), ""]
            if changed_refusals:
                lines += ["| case | %s | %s |" % (base_version, new_version), "|---|---|---|"]
                for k in changed_refusals:
                    lines.append("| `%s` | %s | %s |" % (k, json.dumps(b[k], sort_keys=True), json.dumps(n[k], sort_keys=True)))
                lines.append("")
        facts = [k for k in common if (n[k]["kind"] == "fact" and n[k] != b[k])
                 or n[k].get("compile_seconds") is not None]
        if facts:
            lines += ["Other recorded facts that differ:", "",
                      "| record | %s | %s |" % (base_version, new_version), "|---|---|---|"]
            for k in facts:
                lines.append("| `%s` | %s | %s |" % (k, json.dumps({x: b[k].get(x) for x in FACT if x in b[k]}),
                                                   json.dumps({x: n[k].get(x) for x in FACT if x in n[k]})))
            lines.append("")
        only_new, only_base = sorted(set(n) - set(b)), sorted(set(b) - set(n))
        if only_new:
            lines += ["Only in the %s run: %s." % (new_version, ", ".join("`%s`" % k for k in only_new)), ""]
        if only_base:
            lines += ["Only in the %s run: %s." % (base_version, ", ".join("`%s`" % k for k in only_base)), ""]

    head = ["## Summary", "",
            "| test | spends | programs | refusals and outcomes | sizes changed | refusals changed |",
            "|---|---:|---:|---:|---:|---:|"]
    for title, s, p, r, cs, cr, _, _ in summary:
        head.append("| %s | %d | %d | %d | %d | %d |" % (title, s, p, r, cs, cr))
    head.append("")
    i = lines.index("## %s" % summary[0][0]) if summary else len(lines)
    return "\n".join(lines[:i] + head + lines[i:]) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    ap.add_argument("--distil", metavar="DIR", help="write the baseline from the record files in DIR")
    ap.add_argument("--baseline-version", default="0.4.1")
    a = ap.parse_args()
    if a.distil:
        os.makedirs(os.path.dirname(BASELINE), exist_ok=True)
        with open(BASELINE, "w") as f:
            json.dump(load_records(a.distil), f, indent=1, sort_keys=True)
            f.write("\n")
        print("wrote", BASELINE)
        return 0
    sys.path.insert(0, ROOT)
    version = "0.7.2"
    for f in glob.glob(os.path.join(RECORDS, "*.json")):
        for v in json.load(open(f)).values():
            if isinstance(v, dict) and "compiler_version" in v:
                version = v["compiler_version"]
    text = report(json.load(open(BASELINE)), load_records(RECORDS), version, a.baseline_version)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        f.write(text)
    print("wrote", OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
